# Generated by Django 3.1.6 on 2021-02-02 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=20, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalizacja', models.CharField(max_length=30, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_pracownika', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=40)),
                ('zatrudniony', models.BooleanField(default=True)),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepustki.dzial')),
            ],
        ),
        migrations.CreateModel(
            name='RodzajWpisu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=60, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Przepustka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyjscia', models.DateField(verbose_name='data wyjscia')),
                ('godzina_wyjscia', models.TimeField(verbose_name='godzina wyjscia')),
                ('data_przyjscia', models.DateField(blank=True, null=True, verbose_name='data przyjscia')),
                ('godzina_przyjscia', models.TimeField(blank=True, null=True, verbose_name='godzina przyjscia')),
                ('data_dodania', models.DateTimeField(blank=True, null=True, verbose_name='data dodania')),
                ('cofnieta', models.BooleanField(default=False)),
                ('autor_wpisu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepustki.autor')),
                ('pracownik', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='przepustki.pracownik')),
                ('rodzaj_wpisu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='przepustki.rodzajwpisu')),
            ],
        ),
        migrations.AddField(
            model_name='dzial',
            name='lokalizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='przepustki.lokalizacja'),
        ),
    ]
