# Generated by Django 3.1.6 on 2021-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepustki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dzial',
            name='dzial',
            field=models.CharField(max_length=20),
        ),
    ]
