# Generated by Django 3.1.6 on 2021-02-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepustki', '0002_auto_20210203_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
